version: '2'
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - '3306:3306'

  rails:
    build: .
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: mysql2://root@mysql:3306
    depends_on:
      - mysql
